### Test DCASE Baseline CNN3 on test set ###
# Normally only need to change `ckpt_path`

trainer:
  logger:
      # Logger to save the logs, configs, hyperparameters and checkpoints
      class_path: lightning.pytorch.loggers.TensorBoardLogger
      init_args:
        # Save path
        save_dir: log
        # Sub-path of the save path
        name: cnn3_test

# Path to the checkpoint of trained CNN3
ckpt_path: log/cnn3_train/version_*/checkpoints/***.ckpt

model:
  class_path: model.lit_asc.LitAcousticSceneClassificationSystem
  init_args:
    backbone:
      # A simple 3-layers CNN with 46K params and 29 MMACs
      class_path: model.backbones.DCASEBaselineCnn3
      init_args:
        in_channels: 1
        num_classes: 10
        base_channels: 16
        kernel_size: 7
        dropout: 0.3
    data_augmentation:
      mix_up: null
      mix_style: null
      spec_aug: null
      dir_aug: null
    class_label: scene
    domain_label: device
    spec_extractor:
      class_path: util.Cnn3Mel
      init_args:
        spectrogram_type: magnitude
        hop_length_seconds: 0.02
        win_length_seconds: 0.04
        window_type: hamming_asymmetric
        n_mels: 40
        n_fft: 2048
        fmin: 0
        fmax: 22050
        htk: false
        normalize_mel_bands: false

data:
  class_path: data.data_module.DCASEDataModule
  init_args:
    meta_dir: data/meta_dcase_2024
    audio_dir: ../TAU-urban-acoustic-scenes-2022-mobile-development/development
    batch_size: 512
    num_workers: 8
    pin_memory: true
    sampling_rate: 44100
    test_subset: test