trainer:
  logger:
    class_path: lightning.pytorch.loggers.TensorBoardLogger
    init_args:
      save_dir: log
      name: efficientat_star
  callbacks:
    - class_path: util.OverrideEpochStepCallback
    - class_path: util.FreezeEncoderFinetuneClassifier
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: epoch
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        save_top_k: 1
        monitor: val_acc
        mode: max
        filename: '{epoch}-{val_acc:.4f}'
        save_weights_only: True
  max_epochs: 60

ckpt_path: null

model:
  class_path: model.lit_asc.LitAcousticSceneClassificationSystem
  init_args:
    backbone:
      class_path: model.backbones.PretrainedMN40
      init_args:
        pretrained: /home/work/LDH/mn40_as_ext_mAP_487.pt
        num_classes: 10
    data_augmentation:

      mix_up:
        class_path: util.MixUp
        init_args:
          alpha: 0.3
      mix_style:
        class_path: util.FreqMixStyle
        init_args:
          alpha: 0.3
          p: 0.0 
      dir_aug: null
      spec_aug: null
    class_label: scene
    domain_label: device
    spec_extractor:
      class_path: util.spec_extractor.AugmentMelSTFT
      init_args:
        n_mels: 128
        sr: 32000
        win_length: 800
        hopsize: 320
        n_fft: 1024
        freqm: 48
        timem: 128
        fmin: 0
        fmax: null
        fmin_aug_range: 10
        fmax_aug_range: 2000

data:
  class_path: data.data_module.DCASEDataModule
  init_args:
    meta_dir: /home/work/LDH/easy_dcase_task1/data/meta_dcase_2024
    audio_dir: /home/work/dcase2025/TAU-urban-acoustic-scenes-2022-mobile-development
    batch_size: 64
    num_workers: 12
    pin_memory: true
    sampling_rate: 32000
    train_subset: split25

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0001
    weight_decay: 0.0