### Get the predictions of fine-tuned EfficientAT (as teacher soft labels for knowledge distillation) ###
# Normally only need to change `output_dir`, `predict_subset`, `ckpt_path`

trainer:
  callbacks:
    # Write predictions into the original log path
    - class_path: util.PredictionWriter
      init_args:
        output_dir: log/efficientat_finetune/version_*
        # Perform prediction on train or test subset
        predict_subset: &predict_subset split5
        write_interval: epoch

# Path to the checkpoint of fine-tuned EfficientAT
ckpt_path: log/efficientat_finetune/version_*/checkpoints/***.ckpt

model:
  class_path: model.lit_asc.LitAcousticSceneClassificationSystem
  init_args:
    backbone:
      class_path: model.backbones.EfficientAT
      init_args:
        pretrained: model/efficientat/checkpoints/efficientat_best.pt
        num_classes: 10
    data_augmentation:
      mix_up: null
      mix_style: null
      mir_aug: null
      spec_aug: null
    class_label: scene
    domain_label: device
    spec_extractor:
      class_path: util.AugmentMelSTFT
      init_args:
        n_mels: 128
        sr: 32000
        win_length: 800
        hopsize: 320
        n_fft: 1024
        freqm: 64
        timem: 256
        fmin: 0.0
        fmax: 16000
        fmin_aug_range: 10
        fmax_aug_range: 2000

data:
  class_path: data.data_module.DCASEDataModule
  init_args:
    meta_dir: data/meta_dcase_2024
    audio_dir: ../TAU-urban-acoustic-scenes-2022-mobile-development/development
    batch_size: 256
    num_workers: 4
    pin_memory: true
    sampling_rate: 32000
    # Auto-align with the predict_subset declared above
    predict_subset: *predict_subset